### ISSUE TITLE
Text area font never gets bigger again after it gets made smaller

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#107]
See discussion in https://github.com/melindamorang/blowyourfaceoff/pull/106

Type a ton of text into the text entry box. the font gets smaller. Delete text. The text size stays small. I think the textSize() function needs an else statement that sends it back to its normal default size. Also, is there a way to not hard-code the value in there but grab it from the css file? I couldn't figure out how that would be done.

**Comment by sgriffin231** [comment]
I want to create two classes: one for big and one for small and then just
switch the classes as it passes over the 180 character mark. Stupid
textarea is doing its stupid textarea thing and being different from every
other element ever created. I will fix it next time.

**Comment by melindamorang** [comment]
Sarah fixed this.
