### ISSUE TITLE
Switch themes toggle button

### ISSUE THREAD

**Issue by sgriffin231** [melindamorang/blowyourfaceoff#114]
Switch colors on click (changes page html class). Requires head and script "cleanup" before it will work sitewide.

**Comment by melindamorang** [comment]
I'm not sure if this is the problem you're referring to with this issue, but maybe.  On my Android phone, when I click one of the buttons under the drawing canvas, it turns green.

- When the page first loads, I see the Draw button and the thinnest line button selected with the green outline.
- Select Erase. The Erase button is now completely green.
- Select one of the other line thickness buttons. Erase is now blue again but outlined in green. The line thickness button is completely green. And so on. The most recently selected button is always fully green, and anything else representing a state is outlined in green (correct behavior), but only if it was not the most recently selected button.

This behavior does not happen on my PC.

You can log this as a separate issue if this is not the same thing you're talking about with this one.

**Comment by sgriffin231** [comment]
> I'm not sure if this is the problem you're referring to with this issue, but maybe. On my Android phone, when I click one of the buttons under the drawing canvas, it turns green.
> 
> * When the page first loads, I see the Draw button and the thinnest line button selected with the green outline.
> * Select Erase. The Erase button is now completely green.
> * Select one of the other line thickness buttons. Erase is now blue again but outlined in green. The line thickness button is completely green. And so on. The most recently selected button is always fully green, and anything else representing a state is outlined in green (correct behavior), but only if it was not the most recently selected button.
> 
> This behavior does not happen on my PC.
> 
> You can log this as a separate issue if this is not the same thing you're talking about with this one.

This is the candy vomit thing. lol
I didn't even know about that issue, so this should be logged as a separate issue.

**Comment by sgriffin231** [comment]
Got the basic themes set up. Now I just need to clean up the head sections in the pages, which should wait until after this week's game. But...if you load this branch and change the html theme class to theme-candy-vomit (homepage only), you'll see the change! lol

<img width="1384" alt="Screen Shot 2021-03-28 at 10 03 03 PM" src="https://user-images.githubusercontent.com/73414055/112789606-4ec0c780-9012-11eb-98b6-aefca26c6619.png">
<img width="1387" alt="Screen Shot 2021-03-28 at 10 02 10 PM" src="https://user-images.githubusercontent.com/73414055/112789599-4a94aa00-9012-11eb-8aa6-71951708ba5b.png">

**Comment by melindamorang** [comment]
That is utterly vomitorious!

**Comment by melindamorang** [comment]
Here's some Barf Mode inspiration: https://www.youtube.com/watch?v=m9rmQe_uZnE
I did not have the patience to watch the whole thing, but the guy's commentary is hilarious.

**Comment by melindamorang** [comment]
This seems done. Was there more you wanted to do here, or can we close this?
