### ISSUE TITLE
Put white background box over text on lobby page

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#119]
It's hard to read the text. All the other pages have a white background box so you can see the text. Can we do this for the lobby too?

![image](https://user-images.githubusercontent.com/16789766/113955833-50884900-97d1-11eb-8b65-859593cddce8.png)

**Comment by sgriffin231** [comment]
Crap. Forgot the lobby AGAIN. I'll address after class.

**Comment by melindamorang** [comment]
Fixed in https://github.com/melindamorang/blowyourfaceoff/pull/120
