### ISSUE TITLE
Restructure pages to use shared code for headers and footers and useful things like that

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#16]

**Comment by sgriffin231** [comment]
Just wanted to let you know this is going to be a MAJOR upgrade. We may want to pause updates until this is done. I should be able to finish over weekend of 4/3 & 4/4.

**Comment by melindamorang** [comment]
Okay. Let me know if/when you want help testing it.

**Comment by melindamorang** [comment]
Resolved by https://github.com/melindamorang/blowyourfaceoff/pull/116
