### ISSUE TITLE
For gameplay text inputs, make a larger text area that does word wrapping

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#50]
I tried changing the input type from "text" to "textarea" but this did not magically result in the desired change. Please make it work better.

**Comment by sgriffin231** [comment]
That is because it's its own element and not an input type. If you want to
try, you need to use <textbox> and not <input>. You'll need to change it
everywhere except the database.

**Comment by melindamorang** [comment]
Resolved with https://github.com/melindamorang/blowyourfaceoff/pull/79
