### ISSUE TITLE
Deemphasize the Clear button

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#72]
A couple of people have accidentally hit Clear instead of Submit, thus losing their work.  Please adjust formatting to deemphasize the Clear button.

**Comment by sgriffin231** [comment]
It should probably also say "clear drawing" and be part of the tools under
the image.

**Comment by melindamorang** [comment]
Resolved with https://github.com/melindamorang/blowyourfaceoff/pull/79
