### ISSUE TITLE
New Clear button styling looks weird on Android

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#80]
The new Clear button formatting doesn't look quite right on my Android phone in Chrome:
![Screenshot_20201231-152148_Chrome](https://user-images.githubusercontent.com/16789766/103430787-7ec80e00-4b7c-11eb-84fd-8e1b4aa48534.jpg)

The colors are reversed from what they are on PC, and the Clear button seems too big.

**Comment by sgriffin231** [comment]
This is an old version. Can you try clearing your cache? It works fine on
all of the android devices in our house.

**Comment by melindamorang** [comment]
You're right. My bad. I thought it was picking up the changes because it seemed different, but it looks like it only picked up some of them...?  My phone seems to be weird that way.

**Comment by sgriffin231** [comment]
Honestly, it looks like it just didn't update the css file. All the rest
were as expected.
