### ISSUE TITLE
Drawing with a pen on a Lenovo Yoga Book doesn't stop drawing when you lift the pen

### ISSUE THREAD

**Issue by melindamorang** [melindamorang/blowyourfaceoff#94]
User has a Yoga book c930. "I can use the pen on any of my screens I was choosing to use it like my mouse but it would keep the ink running om the screen even when I lifted the pen.  It was accurate just never ending.  It would also sometimes do this with when using the mouse pad and not the pen. The ink just wouldn't stop so I couldn't lift and start a new line.  The pen came with the laptop tablet hybrid that the Lenovo Yoga book c390 is.  Chrome for browser."

**Comment by sgriffin231** [comment]
I have a Wacom tablet you can use if you need to solve this problem. Or I can investigate with Jacob.

**Comment by melindamorang** [comment]
Nice. Can you reproduce the problem on it?

**Comment by sgriffin231** [comment]
I'll ask Isaac to try his first. I haven't actually used it yet....

**Comment by sgriffin231** [comment]
**From Isaac**

> When I used my drawing tablet:
> 
> - Drawing a line made it so it kept on drawing even when the pen was just hovering the tablet and even when I wasn't in the drawing space. I needed to tap the tablet to make it stop.
> - Making dots was perfectly fine.
> - Here is the game code to see the drawings I did: 435744

**Comment by sgriffin231** [comment]
If you want me to drop off my tablet, I can have Eric leave it on the porch tomorrow morning. Or Isaac can work with Jacob to figure it out since he built the original anyway. He might just know off the top of his head what the problem is.

**Comment by melindamorang** [comment]
Thanks both of you!  Can you please ask Isaac to clear his browser cache and try again really quickly?  I have temporarily pushed something that fixes a liney problem with a mouse that might also fix this issue. If not, then maybe Isaac and Jacob should try to figure it out...

**Comment by melindamorang** [comment]
Well, it's definitely something to do with the event listeners for the canvas, but beyond that I don't know. I'm going to go do something else for a while.

**Comment by sgriffin231** [comment]
Isaac said it still doesn't work. Jacob is going to work on it and have
Isaac test. I told him there is a new database to update to.

**Comment by sgriffin231** [comment]
Can you make that last request with Jacob's changes live so Isaac can test?

**Comment by melindamorang** [comment]
I just pushed a change that fixes a javascript error on Android and may fix some other drawing problems. Sarah, could you please as Isaac to re-test this with his drawing pen? I'm not terribly hopeful, but it's worth a try.

**Comment by melindamorang** [comment]
Isaac says the experience is better but still "wonky" and "janky". I'm going to send this to Autumn, who reported the problem, and see if it's fixed for her.

**Comment by melindamorang** [comment]
Autumn tested the update and said everything is working satisfactorily now with her drawing pen. I'm going to close this issue. I will look into Isaac's "wonky" "janky" problem separately.
